// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project002.Repository.Models;

#nullable disable

namespace Project002.Repository.Migrations
{
    [DbContext(typeof(Dbcontext))]
    [Migration("20240521140243_hi")]
    partial class hi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArmourSamurai", b =>
                {
                    b.Property<int>("ArmourId")
                        .HasColumnType("int");

                    b.Property<int>("SamuraiId")
                        .HasColumnType("int");

                    b.HasKey("ArmourId", "SamuraiId");

                    b.HasIndex("SamuraiId");

                    b.ToTable("ArmourSamurai");
                });

            modelBuilder.Entity("Project002.Repository.Models.Armour", b =>
                {
                    b.Property<int?>("ArmourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ArmourId"), 1L, 1);

                    b.Property<string>("ArmourDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArmourName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArmourId");

                    b.ToTable("Armour");
                });

            modelBuilder.Entity("Project002.Repository.Models.Clan", b =>
                {
                    b.Property<int?>("ClanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ClanId"), 1L, 1);

                    b.Property<string>("ClanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SamuraiId")
                        .HasColumnType("int");

                    b.HasKey("ClanId");

                    b.HasIndex("SamuraiId");

                    b.ToTable("Clan");
                });

            modelBuilder.Entity("Project002.Repository.Models.FrontPage", b =>
                {
                    b.Property<int?>("FrontPageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("FrontPageId"), 1L, 1);

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FrontPageId");

                    b.ToTable("FrontPage");
                });

            modelBuilder.Entity("Project002.Repository.Models.Horse", b =>
                {
                    b.Property<int?>("HorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("HorseId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SamuraiId")
                        .HasColumnType("int");

                    b.HasKey("HorseId");

                    b.HasIndex("SamuraiId");

                    b.ToTable("Horse");
                });

            modelBuilder.Entity("Project002.Repository.Models.Samurai", b =>
                {
                    b.Property<int>("SamuraiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SamuraiId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SamuraiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SamuraiId");

                    b.ToTable("Samurai");
                });

            modelBuilder.Entity("Project002.Repository.Models.War", b =>
                {
                    b.Property<int?>("WarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("WarId"), 1L, 1);

                    b.Property<int?>("DeathCount")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarId");

                    b.ToTable("War");
                });

            modelBuilder.Entity("Project002.Repository.Models.Weapon", b =>
                {
                    b.Property<int?>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("WeaponId"), 1L, 1);

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeaponName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponId");

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("SamuraiWeapon", b =>
                {
                    b.Property<int>("SamuraiId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("SamuraiId", "WeaponId");

                    b.HasIndex("WeaponId");

                    b.ToTable("SamuraiWeapon");
                });

            modelBuilder.Entity("ArmourSamurai", b =>
                {
                    b.HasOne("Project002.Repository.Models.Armour", null)
                        .WithMany()
                        .HasForeignKey("ArmourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project002.Repository.Models.Samurai", null)
                        .WithMany()
                        .HasForeignKey("SamuraiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project002.Repository.Models.Clan", b =>
                {
                    b.HasOne("Project002.Repository.Models.Samurai", "Samurai")
                        .WithMany("Clan")
                        .HasForeignKey("SamuraiId");

                    b.Navigation("Samurai");
                });

            modelBuilder.Entity("Project002.Repository.Models.Horse", b =>
                {
                    b.HasOne("Project002.Repository.Models.Samurai", "Samurai")
                        .WithMany("Horse")
                        .HasForeignKey("SamuraiId");

                    b.Navigation("Samurai");
                });

            modelBuilder.Entity("SamuraiWeapon", b =>
                {
                    b.HasOne("Project002.Repository.Models.Samurai", null)
                        .WithMany()
                        .HasForeignKey("SamuraiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project002.Repository.Models.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project002.Repository.Models.Samurai", b =>
                {
                    b.Navigation("Clan");

                    b.Navigation("Horse");
                });
#pragma warning restore 612, 618
        }
    }
}
